# Generated by Django 4.1.1 on 2022-12-29 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('new', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('discription', models.TextField()),
                ('img', models.ImageField(upload_to='pics/')),
                ('username', models.CharField(max_length=200)),
                ('catagory', models.CharField(default='bikes', editable=False, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buyer_id', models.IntegerField()),
                ('Buyer_name', models.CharField(max_length=100)),
                ('seller_name', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
                ('Product_name', models.CharField(max_length=200)),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 12, 29, 21, 28, 36, 608829), editable=False)),
                ('EndTime', models.DateTimeField(default=datetime.datetime(2022, 12, 29, 22, 28, 36, 608829), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('new', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('discription', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('username', models.CharField(max_length=200)),
                ('catagory', models.CharField(default='cars', editable=False, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='laptops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('new', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('discription', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('username', models.CharField(max_length=200)),
                ('catagory', models.CharField(default='laptops', editable=False, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('new', models.BooleanField(default=False)),
                ('city', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('discription', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('username', models.CharField(max_length=200)),
                ('catagory', models.CharField(default='mobiles', editable=False, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.IntegerField()),
                ('Buyer_name', models.CharField(max_length=100)),
                ('Product_catagory', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 12, 29, 21, 28, 36, 620337), editable=False)),
                ('rate', models.IntegerField(blank=True)),
                ('comment', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=100)),
                ('user_contact', models.CharField(max_length=100)),
                ('user_address', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
