# Generated by Django 4.1.1 on 2022-12-29 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_buyer_info_endtime_alter_buyer_info_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer_info',
            name='Buyer_id',
        ),
        migrations.AlterField(
            model_name='buyer_info',
            name='EndTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 22, 30, 36, 265808), editable=False),
        ),
        migrations.AlterField(
            model_name='buyer_info',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 21, 30, 36, 265808), editable=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 21, 30, 36, 265808), editable=False),
        ),
    ]
