# Generated by Django 4.1.1 on 2022-12-30 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_buyer_info_buyer_id_alter_buyer_info_endtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_info',
            name='varification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buyer_info',
            name='EndTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 21, 24, 42, 171170), editable=False),
        ),
        migrations.AlterField(
            model_name='buyer_info',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 20, 24, 42, 171170), editable=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 20, 24, 42, 171170), editable=False),
        ),
    ]
