# Generated by Django 4.1.1 on 2023-01-01 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_bikes_disable_cars_disable_laptops_disable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer_info',
            name='EndTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 2, 1, 39, 38, 369593), editable=False),
        ),
        migrations.AlterField(
            model_name='buyer_info',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 2, 0, 39, 38, 369593), editable=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 2, 0, 39, 38, 385251), editable=False),
        ),
    ]
