# Generated by Django 4.1.1 on 2023-01-01 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_buyer_info_endtime_alter_buyer_info_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer_info',
            name='EndTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 2, 2, 6, 48, 249237), editable=False),
        ),
        migrations.AlterField(
            model_name='buyer_info',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 2, 1, 6, 48, 249237), editable=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 2, 1, 6, 48, 249237), editable=False),
        ),
    ]
